version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: fact-guard-qdrant-prod
    ports:
      - "6333:6333"
    volumes:
      - qdrant_prod_data:/qdrant/storage
    restart: unless-stopped
    
  ollama:
    image: ollama/ollama:latest
    container_name: fact-guard-ollama-prod
    ports:
      - "11434:11434"
    volumes:
      - ollama_prod_data:/root/.ollama
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: fact-guard-api-prod
    ports:
      - "8000:8000"
    volumes:
      - uploads_prod_data:/app/uploads
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - DEBUG=false
    depends_on:
      - qdrant
      - ollama
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    container_name: fact-guard-ui-prod
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  qdrant_prod_data:
  ollama_prod_data:
  uploads_prod_data: